  services:
    spark:
      build:
        context: .
        dockerfile: Dockerfile  
      image: spark-neo4j:latest
      container_name: spark_container
      ports:
        - "8080:8080"  # Puerto de la UI de Spark
        - "7077:7077"  # Puerto del nodo principal de Spark
      environment:
        - SPARK_MODE=master  # Configura Spark como el nodo principal
        - SPARK_MASTER_HOST=spark_container
        - SPARK_MASTER_PORT=7077 
        - SPARK_MASTER_MEMORY=2g 
      volumes:
        - ./spark_logs:/opt/bitnami/spark/logs  # Monta un volumen para los logs
      depends_on:
        - neo4j
      networks:
        - spark-neo4j-net

    neo4j:
      image: neo4j:5.10.0
      container_name: neo4j_container
      ports:
        - "7474:7474"  # Puerto para la UI de Neo4j
        - "7687:7687"  # Puerto para la conexión Bolt
      environment:
        - NEO4J_AUTH=neo4j/badpassword  
      volumes:
        - neo4j_data:/var/lib/neo4j/data 
        - neo4j_import:/var/lib/neo4j/import  
      networks:
        - spark-neo4j-net

  volumes:
    neo4j_data:
    neo4j_import:

  networks:
    spark-neo4j-net:
      driver: bridge