services:
  spark:
    image: jupyter/pyspark-notebook:x86_64-ubuntu-22.04
    container_name: spark-container
    ports:
      - "8888:8888"
    volumes:
      - C:\Users\todom\Repositorios\Bases-de-datos-2-Proyecto-2:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - PYSPARK_DRIVER_PYTHON=jupyter
      - PYSPARK_DRIVER_PYTHON_OPTS="notebook"
    networks:
      - default
  neo4j:
    container_name: neo4j
    image: neo4j:ubi9
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/badpassword
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"] 
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - default
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - default
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  neo4j_data:
  neo4j_logs:
  postgres_data:
  pgadmin_data:
networks:
  default:
    driver: bridge